### ISSUE TITLE
Consult with MariaDB Master Slave Setup

### ISSUE THREAD

**Issue by ghost** [mariadb-faisalsaeed/documentation#1]
Hi Faisal and thank you so much for this guide. It's very useful.

I follow step by step but I can't successfully replicate it.

In my virtual lab I use CentOS 8 and MariaDB 10.5, maybe something changed and that's why I have errors and I can't achieve the Master, Slave with GTID replication.

That's why I'm asking you if there's a possibility that you can update this guide with the new versions of CentOS and MariaDB.

Thank you very much!
I'm waiting for your answer.

###########################################
This is the guide that i follow:
https://github.com/mariadb-faisalsaeed/documentation/blob/master/MariaDB%20Master%20Slave%20Setup.md

**Comment by chrispage1** [comment]
I've just been setting up with MariaDB 10.5 and there are a few things you need to change.

Once you've got your replication running, you need to configure your maxscale DB users with slightly different permissions... I'll refer to the usernames as in the documentation. Here's the amended block - 

For `maxuser` there are two new grants, access to mysql.proxies_priv & mysql.columns_priv

For `maxmon` you need to grant REPLICATION SLAVE permissions.

```mysql
# USER (maxuser): ReadWrite-Splitter user, this user is going to be a
# part of the basic configuration

MariaDB [(none)]> CREATE USER 'maxuser'@'%' IDENTIFIED BY 'secretpassword';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SELECT ON mysql.user TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SELECT ON mysql.db TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SELECT ON mysql.tables_priv TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SELECT ON mysql.roles_mapping TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SELECT ON mysql.proxies_priv TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SELECT ON mysql.columns_priv TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SHOW DATABASES ON *.* TO 'maxuser'@'%';
Query OK, 0 rows affected (0.001 sec)

# USER (maxmon): MariaDBMon user
# user created for the monitor MariaDBMon, to pull state,
# do the failover, switchover and rejoin servers part of existing clusters

MariaDB [(none)]> CREATE USER maxmon@'%' IDENTIFIED BY 'secretpassword';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> GRANT SUPER, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO maxmon@'%';
Query OK, 0 rows affected (0.001 sec)

MariaDB [(none)]> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.001 sec)
```

I hope this helps! I've finally managed to get a successfully working maxscale - 

```
root@ha1:/var/lib/maxscale/maxscale.cnf.d# maxctrl list servers
┌────────────┬──────────────┬──────┬─────────────┬─────────────────┬─────────┐
│ Server     │ Address      │ Port │ Connections │ State           │ GTID    │
├────────────┼──────────────┼──────┼─────────────┼─────────────────┼─────────┤
│ mariadb-90 │ 192.168.1.90 │ 3307 │ 0           │ Master, Running │ 0-90-57 │
├────────────┼──────────────┼──────┼─────────────┼─────────────────┼─────────┤
│ mariadb-91 │ 192.168.1.91 │ 3307 │ 0           │ Slave, Running  │ 0-90-57 │
├────────────┼──────────────┼──────┼─────────────┼─────────────────┼─────────┤
│ mariadb-92 │ 192.168.1.92 │ 3307 │ 0           │ Slave, Running  │ 0-90-57 │
└────────────┴──────────────┴──────┴─────────────┴─────────────────┴─────────┘
root@ha1:/var/lib/maxscale/maxscale.cnf.d# maxctrl call command mariadbmon switchover MariaDB-Monitor mariadb-92 mariadb-90
OK
root@ha1:/var/lib/maxscale/maxscale.cnf.d# maxctrl list servers
┌────────────┬──────────────┬──────┬─────────────┬─────────────────┬─────────┐
│ Server     │ Address      │ Port │ Connections │ State           │ GTID    │
├────────────┼──────────────┼──────┼─────────────┼─────────────────┼─────────┤
│ mariadb-90 │ 192.168.1.90 │ 3307 │ 0           │ Slave, Running  │ 0-90-57 │
├────────────┼──────────────┼──────┼─────────────┼─────────────────┼─────────┤
│ mariadb-91 │ 192.168.1.91 │ 3307 │ 0           │ Slave, Running  │ 0-90-57 │
├────────────┼──────────────┼──────┼─────────────┼─────────────────┼─────────┤
│ mariadb-92 │ 192.168.1.92 │ 3307 │ 0           │ Master, Running │ 0-90-57 │
└────────────┴──────────────┴──────┴─────────────┴─────────────────┴─────────┘
```

**Comment by ghost** [comment]
Thank you very much for your comments @chrispage1 
I follow all the steps mentioned by @mariadb-faisalsaeed both in this guide and in his YouTube videos and this is where I have errors to follow:

**I get these values from my MariaDB Master:**
```
mariadb01.localdomain [(none)]> show master status;
+--------------------+----------+--------------+------------------+
| File               | Position | Binlog_Do_DB | Binlog_Ignore_DB |
+--------------------+----------+--------------+------------------+
| mariadb-bin.000001 |     4018 |              |                  |
+--------------------+----------+--------------+------------------+
1 row in set (0.000 sec)

mariadb01.localdomain [(none)]> select binlog_gtid_pos('mariadb-bin.000001', 4018);
+---------------------------------------------+
| binlog_gtid_pos('mariadb-bin.000001', 4018) |
+---------------------------------------------+
| 0-1000-13                                   |
+---------------------------------------------+
1 row in set (0.000 sec)

mariadb01.localdomain [(none)]>
```

**I get these values from my MariaDB Slave:**
```
[root@mariadb02 mysql]# mariadb
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 14
Server version: 10.5.4-MariaDB-log MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mariadb02.localdomain [(none)]> stop slave;
Query OK, 0 rows affected, 1 warning (0.000 sec)

mariadb02.localdomain [(none)]> show master status;
+--------------------+----------+--------------+------------------+
| File               | Position | Binlog_Do_DB | Binlog_Ignore_DB |
+--------------------+----------+--------------+------------------+
| mariadb-bin.000001 |     3228 |              |                  |
+--------------------+----------+--------------+------------------+
1 row in set (0.000 sec)

mariadb02.localdomain [(none)]> select binlog_gtid_pos('mariadb-bin.000001', 3228);
+---------------------------------------------+
| binlog_gtid_pos('mariadb-bin.000001', 3228) |
+---------------------------------------------+
| 0-2000-8                                    |
+---------------------------------------------+
1 row in set (0.001 sec)

mariadb02.localdomain [(none)]> STOP SLAVE;
Query OK, 0 rows affected, 1 warning (0.000 sec)

mariadb02.localdomain [(none)]> select binlog_gtid_pos('mariadb-bin.000001', 3228);
+---------------------------------------------+
| binlog_gtid_pos('mariadb-bin.000001', 3228) |
+---------------------------------------------+
| 0-2000-8                                    |
+---------------------------------------------+
1 row in set (0.000 sec)

mariadb02.localdomain [(none)]> RESET SLAVE;
Query OK, 0 rows affected (0.000 sec)

mariadb02.localdomain [(none)]> show master status;
+--------------------+----------+--------------+------------------+
| File               | Position | Binlog_Do_DB | Binlog_Ignore_DB |
+--------------------+----------+--------------+------------------+
| mariadb-bin.000001 |     3228 |              |                  |
+--------------------+----------+--------------+------------------+
1 row in set (0.000 sec)

mariadb02.localdomain [(none)]> select binlog_gtid_pos('mariadb-bin.000001', 3228);
+---------------------------------------------+
| binlog_gtid_pos('mariadb-bin.000001', 3228) |
+---------------------------------------------+
| 0-2000-8                                    |
+---------------------------------------------+
1 row in set (0.000 sec)

mariadb02.localdomain [(none)]> set global gtid_slave_pos="";
ERROR 1948 (HY000): Specified value for @@gtid_slave_pos contains no value for replication domain 0. This conflicts with the binary log which contains GTID 0-2000-8. If MASTER_GTID_POS=CURRENT_POS is used, the binlog position will override the new value of @@gtid_slave_pos
mariadb02.localdomain [(none)]>
```

...and after that **ERROR 1948** I don't want to go on because I want to know how @mariadb-faisalsaeed  got an empty GTID in the slave node.

The installation of both virtual machines is fresh and I don't know when the slave node gets a GTID. (0-2000-8)?¿?¿?¿? The only thing I did on the slave database was "`mysql_secure_installation`"

What can I do so that the slave node does not get a GTID? And then can I run the next query:

`CHANGE MASTER TO MASTER_HOST='192.168.XXX.XXX', MASTER_PORT=3306, MASTER_USER='repl_user', MASTER_PASSWORD='secretpassword', MASTER_USE_GTID=current_pos;`

I have also followed the steps published [here](https://www.transip.co.uk/knowledgebase/entry/1551-solving-mariadb-master-slave-problems/), but I have not been successful...

What am I doing wrong or what am I not seeing?
Sorry, but I'm pretty new to the database world.

Greetings and I look forward to your answers.
Thank you very much.

**Comment by faizalrf** [comment]
Hi Chrispage1,

Thank you for adding on the additional grants required for MaxScale 2.5 on
MariaDB 10.5 :)

This readme is a bit outdated, I will update it and add an additional
section for the latest release and it's requirements.

Thanks again.

Best Regards,
*Faisal Saeed* | *Senior Solution Engineer*
MariaDB Corporation | Tel: +65 9386 5771 | faisal@mariadb.com | Skype:
faisalee

<https://mariadb.com/>

**Comment by faizalrf** [comment]
Hi Germán Rivas,

Here is the thing, Since you mentioned you have only done the
"mysql_secure_installation", this will generate some binary logs and your
GTID will increase. "mysql_secure_installation" is supposed to be done
before you enable binary logs. Here are the steps again:

1. Two fresh CentOS servers with base MariaDB installed
2. Execute mysql_secure_instalallation
3. Setup server.cnf to enable binlogs and server_id values
4. follow on with the steps that you are trying to do, should give you an
empty GTID, to begin with on the Slave Node.

But if you already have a GTID on the SLAVE node, the best thing to do
would be to take a fresh backup form the Master and restore it on the Slave
node and re-setup the replication. I will create a document for that
sometime this week :)

But if you want to continue from your current situation, you can do the
following on the slave node:

1. STOP SLAVE; RESET MASTER; RESET SLAVE; RESET SLAVE ALL;
2. check your current GTID, it should be empty now.
3. Now you can use the SET GLOBAL GTID_SLAVE_POS = '<GTID FROM MASTER>';
4. CHANGE MASTER ... MASTER_USE_GTID=CURRENT_POS;

This will force the slave to continue from the current position where the
MASTER is right now. This can create some data discrepancies as you might
be missing some transactions, but since you have just done
"mysql_secure_installation" and nothing else, it should be fine.

Remember to create the new user on the SLAVE that you have already created
on the MASTER node, This use might not have replicated on the SLAVE and
since you are doing a force GTID to start from master's current position,
those binary logs will be skipped.
I would still suggest resetting your VMs and follow the steps I mentioned,
in the beginning, to be sure that you get expected results as per this
document :)

Just don't do any tasks on the slave, like mysql_secure_installation or any
other DDL, DML (INSERT, UPDATE, DELETE)  that can create a mismatching GTID
on the SLAVE node. All the transactions should come from the MASTER through
replication. The slave should be used only for SELECT statements.

Best Regards,
*Faisal Saeed* | *Senior Solution Engineer*
MariaDB Corporation | Tel: +65 9386 5771 | faisal@mariadb.com | Skype:
faisalee

<https://mariadb.com/>

**Comment by chrispage1** [comment]
@grmnrvs I used the second trick from @mariadb-faisalsaeed where you run reset master on the slave to clear the binlogs. Only perform this procedure if you're confident both environments are the same and you haven't performed any additional updates on the slave. It works nicely

**Comment by faizalrf** [comment]
@grmnrvs let us know if your problem is solved. The steps are accurate and should work for both CentOS 7/8. As I have recommended you can either:

1. Do a fresh start, don't enable binary logs until you have done the `mysql_secure_installation` 
2. Follow the remaining steps as documented

OR

1. On your SLAVE, do a RESET MASTER; RESET SLAVE ALL;
2. Set up replication as per normal using the GTID of the MASTER node

The second step is meant to be used with extreme care and only when you are 100% sure that as far as the data is concerned, both nodes are identical. 

If you already have data and you feel there may be a mismatch of data between the nodes, you would need to use `mariabackup` and take a full backup from your primary server, restore that backup on your SLAVE and then set it up as a slave.

I will try to upload another guide on how to setup a new node in a cluster and share it here in this thread but for now, you know what to do already 👍 

Cheers,
Faisal.

**Comment by ghost** [comment]
Thank you very much @mariadb-faisalsaeed  and @chrispage1  for your comments. After having performed this test:

```
On your SLAVE, do a RESET MASTER; RESET SLAVE ALL;
Set up replication as per normal using the GTID of the MASTER node
```

These are the results the slave gives me, let me show you:

```
[root@mariadb02 ~]# systemctl start mariadb
[root@mariadb02 ~]# mariadb
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.4-MariaDB-log MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mariadb02.localdomain [(none)]> stop slave;
Query OK, 0 rows affected, 1 warning (0.000 sec)

mariadb02.localdomain [(none)]> reset master;
Query OK, 0 rows affected (0.004 sec)

mariadb02.localdomain [(none)]> reset slave all;
Query OK, 0 rows affected (0.001 sec)

mariadb02.localdomain [(none)]> show master status;
+--------------------+----------+--------------+------------------+
| File               | Position | Binlog_Do_DB | Binlog_Ignore_DB |
+--------------------+----------+--------------+------------------+
| mariadb-bin.000001 |      330 |              |                  |
+--------------------+----------+--------------+------------------+
1 row in set (0.001 sec)

mariadb02.localdomain [(none)]> select binlog_gtid_pos('mariadb-bin.000001', 330);                                                                                                                                                           
+--------------------------------------------+
| binlog_gtid_pos('mariadb-bin.000001', 330) |
+--------------------------------------------+
|                                            |
+--------------------------------------------+
1 row in set (0.001 sec)

mariadb02.localdomain [(none)]> set global gtid_slave_pos="";
Query OK, 0 rows affected (0.009 sec)

mariadb02.localdomain [(none)]> CHANGE MASTER TO MASTER_HOST='192.168.153.189', MASTER_PORT=3306, MASTER_USER='repl_user', MASTER_PASSWORD='secretpassword', MASTER_USE_GTID=current_pos;
Query OK, 0 rows affected (0.007 sec)

mariadb02.localdomain [(none)]> start slave;
Query OK, 0 rows affected (0.007 sec)

mariadb02.localdomain [(none)]> show slave status\G
*************************** 1. row ***************************
                Slave_IO_State: Waiting for master to send event
                   Master_Host: 192.168.153.189
                   Master_User: repl_user
                   Master_Port: 3306
                 Connect_Retry: 60
               Master_Log_File: mariadb-bin.000002
           Read_Master_Log_Pos: 344
                Relay_Log_File: mariadb02-relay-bin.000002
                 Relay_Log_Pos: 2549
         Relay_Master_Log_File: mariadb-bin.000001
              Slave_IO_Running: Yes
             Slave_SQL_Running: No
               Replicate_Do_DB:
           Replicate_Ignore_DB:
            Replicate_Do_Table:
        Replicate_Ignore_Table:
       Replicate_Wild_Do_Table:
   Replicate_Wild_Ignore_Table:
                    Last_Errno: 1032
                    Last_Error: Could not execute Delete_rows_v1 event on table my sql.global_priv; Can't find record in 'global_priv', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mariadb-bin.000001, end_log_pos 2499
                  Skip_Counter: 0
           Exec_Master_Log_Pos: 2248
               Relay_Log_Space: 5334
               Until_Condition: None
                Until_Log_File:
                 Until_Log_Pos: 0
            Master_SSL_Allowed: No
            Master_SSL_CA_File:
            Master_SSL_CA_Path:
               Master_SSL_Cert:
             Master_SSL_Cipher:
                Master_SSL_Key:
         Seconds_Behind_Master: NULL
 Master_SSL_Verify_Server_Cert: No
                 Last_IO_Errno: 0
                 Last_IO_Error:
                Last_SQL_Errno: 1032
                Last_SQL_Error: Could not execute Delete_rows_v1 event on table my sql.global_priv; Can't find record in 'global_priv', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mariadb-bin.000001, end_log_pos 2499
   Replicate_Ignore_Server_Ids:
              Master_Server_Id: 1000
                Master_SSL_Crl:
            Master_SSL_Crlpath:
                    Using_Gtid: Current_Pos
                   Gtid_IO_Pos: 0-1000-13
       Replicate_Do_Domain_Ids:
   Replicate_Ignore_Domain_Ids:
                 Parallel_Mode: optimistic
                     SQL_Delay: 0
           SQL_Remaining_Delay: NULL
       Slave_SQL_Running_State:
              Slave_DDL_Groups: 2
Slave_Non_Transactional_Groups: 3
    Slave_Transactional_Groups: 0
1 row in set (0.001 sec)

mariadb02.localdomain [(none)]>
```

What I will do now is perform this test:

```
1. Two fresh CentOS servers with base MariaDB installed
2. Execute mysql_secure_instalallation
3. Setup server.cnf to enable binlogs and server_id values
4. follow on with the steps that you are trying to do, should give you an
empty GTID, to begin with on the Slave Node.
```
...and I'll inform you of the results as soon as possible.

I hope I'm lucky this time. A hug,
Germán Rivas.

**Comment by ghost** [comment]
Well, I followed these steps:

```
1. Two fresh CentOS servers with base MariaDB installed
2. Execute mysql_secure_instalallation
3. Setup server.cnf to enable binlogs and server_id values
4. follow on with the steps that you are trying to do, should give you an
empty GTID, to begin with on the Slave Node.
```
...and it worked fine. I'm very happy with the results.

I was testing the two virtual machines, turning off, restarting, turning on, stopping and starting the MariaDB service and everything worked very well, just as I expected.

At some point in all the tests I did I made a mistake without meaning to and this happens to me that I don't know how to solve it, let me show you:

Every 1,0s: maxctrl list servers    maxscale.localdomain: Thu Aug  6 15:12:08 2020

```
┌─────────┬─────────────────┬──────┬─────────────┬─────────────────┬───────────┐
│ Server  │ Address         │ Port │ Connections │ State           │ GTID      │
├─────────┼─────────────────┼──────┼─────────────┼─────────────────┼───────────┤
│ Primary │ 192.168.153.189 │ 3306 │ 0           │ Running         │ 0-1000-23 │
├─────────┼─────────────────┼──────┼─────────────┼─────────────────┼───────────┤
│ Replica │ 192.168.153.190 │ 3306 │ 0           │ Master, Running │ 0-2000-24 │
└─────────┴─────────────────┴──────┴─────────────┴─────────────────┴───────────┘
```

The primary server's GTID is different from the replica server's GTID, these are the messages I see from:
`tail -f /var/log/maxscale/maxscale.log` after executing the following command:

`maxctrl call command mariadbmon switchover MariaDB-Monitor <...> <...>`

```
2020-08-06 14:52:41   warning: [mariadbmon] Automatic rejoin was not attempted on server 'Replica' even though it is a valid candidate. Will keep retrying with this message suppressed for all servers. Errors:
gtid_current_pos of 'Replica' (0-2000-24) is incompatible with gtid_binlog_pos of 'Primary' (0-1000-23).
2020-08-06 14:53:17   error  : [mariadbmon] 'Replica' is not a valid promotion target for switchover because it is not replicating from 'Primary'.
2020-08-06 14:53:17   error  : [mariadbmon] Switchover cancelled.
```

**Comment by faizalrf** [comment]
It seems you have accidentally changed data on a "Slave" node and the GTID has a mismatch. 

There can be many reasons which can lead to this situation. But the result is the same. Mismatching GTID on Primary vs Replica.

Here is what you can do to try to resolve this. 

1. Take a fresh `mariabackup` from "Primary" node and restore it on Replica and set it up as a fresh slave. This is the ideal way of rebuilding a slave. because once you have a GTID mismatch, the data is no longer trustworthy and needs to be manually synced up through rebuilding the slave.

OR

2. If you are just testing and want to let the replication continue, data is not important, you can do the following to reset your replication.

- stop MaxScale service `systemctl stop maxscale`
- On MASTER and SLAVE nodes, drop your any new databases & tables that you might have created. This is to bring the two servers in ZERO meter state :)

On Your `Primary` Node which is supposed to be the MASTER, do the following to reset it's binlog / GRID related data.

```SQL
stop slave;
reset master;
reset slave;
reset slave all;
set global gtid_slave_pos='';
set global read_only=0;
```

On your `Replica` Node, which is supposed to be the SLAVE, do the following to RESET it completely and rejoin the Primary node as  a SLAVE

```SQL
stop slave;
reset master;
reset slave;
reset slave all;
set global read_only=1;
set global gtid_slave_pos='';
change master to master_host='192.168.153.189', master_user='maxuser', master_password='<Your maxuser Password>', master_port=3306, master_use_gtid=current_pos;
start slave;
```

- Start MaxScale service `systemctl start maxscale`

You should now have the setup in the original state :)

**_Note:_** The above assumes that you are using `maxuser` account in MaxScale as the Monitor User, if you have a different username, please use that user and its password according to your setup.

Please take note that the above is only to be used when the data in the databases is not important and you want to reset your setup to a default state!

For a proper rebuild, use `mariabackup` from the desired node and restore it on the node that is supposed to be the SLAVE, that is the recommended way of rebuilding a slave where data is important and cannot be discarded :)

One more thing, make sure you have `log_bin` and `log_slave_updates` enabled on both of the MariaDB nodes. This is important for failover.

Cheers,
Faisal.

**Comment by ghost** [comment]
Thank you @mariadb-faisalsaeed for your patience and your great explanations, I really appreciate them and I am learning from your knowledge.

At some point in your spare time do you think you could explain a guide about `MariaBackup`, how it is used in a high availability/failover environment?

Thanks again,
German

**Comment by faizalrf** [comment]
@grmnrvs I am very happy that you found this helpful! 

I have just done a quick recording on `MariaBackup` and adding a new node to an existing setup. 

You might have already seen it but, sharing my YouTube link as well https://www.youtube.com/playlist?list=PLb88NRKTvnTycKj7X0GKJ4hPoixVrQ4z6 This playlist contains everything we have discussed here, the 4th video was added few minutes back and it covers the `MariaBackup`, did this on your request, hope this will find it to be as useful :)

Cheers,
Faisal.
